// Certificate links are kept in one array so they are easy to audit and maintain.
const CERTIFICATE_LINKS = [
  'https://drive.google.com/file/d/1Z4Ro5ee7DTZ6JYdnPnVYELwwKPqmzRUr/view?usp=sharing',
  'https://drive.google.com/file/d/13kuY_jdSTHybGCdvMToCQYanizwHZuZS/view?usp=drive_link',
  'https://drive.google.com/file/d/1OMLBG47uWAXbR0-kXWDqGAC1d0oofZTL/view?usp=sharing',
  'https://drive.google.com/file/d/13dbjOumrcogdoFqtp6ACnCfNDPJ6-rcn/view?usp=sharing'
];

const pageOrder=['index.html','profile.html','skills.html','projects.html','certificates.html'];
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];

function initMenu(){const toggle=$('.menu-toggle'),nav=$('.site-nav');if(!toggle||!nav)return;toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});$$('.site-nav a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));}
function initTheme(){const button=$('.theme-toggle');if(!button)return;const saved=localStorage.getItem('portfolio-theme');if(saved)document.documentElement.dataset.theme=saved;button.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('portfolio-theme',next)})}
function initReveal(){const items=$$('.reveal');if(!('IntersectionObserver' in window)||reducedMotion){items.forEach(item=>item.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});items.forEach(item=>observer.observe(item));}
function initProgress(){const bar=$('.scroll-progress span'),rocket=$('.rocket-button'),ring=$('.rocket-progress');const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;const percent=max>0?(scrollY/max)*100:0;if(bar)bar.style.width=`${percent}%`;if(ring)ring.style.setProperty('--progress',`${percent}%`);if(rocket)rocket.classList.toggle('visible',scrollY>300)};addEventListener('scroll',update,{passive:true});update()}
function initTyping(){const target=$('.typing-text');if(!target)return;const words=['Android Developer','Java Developer','Backend Engineer'];let word=0,index=0,deleting=false;const tick=()=>{if(reducedMotion){target.textContent=words[0];return}const current=words[word];target.textContent=current.slice(0,index);if(!deleting&&index<current.length)index++;else if(deleting&&index>0)index--;else{deleting=!deleting;if(!deleting)word=(word+1)%words.length}setTimeout(tick,deleting?45:index===current.length?1700:85)};tick()}
function initCounters(){const counters=$$('.counter');if(!counters.length)return;const count=element=>{const end=Number(element.dataset.target),start=performance.now(),duration=1200;const step=now=>{const progress=Math.min((now-start)/duration,1);element.textContent=Math.floor(progress*end);if(progress<1)requestAnimationFrame(step)};if(reducedMotion){element.textContent=end;return}requestAnimationFrame(step)};if(reducedMotion){counters.forEach(count);return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){count(entry.target);observer.unobserve(entry.target)}}),{threshold:.6});counters.forEach(item=>observer.observe(item))}
function formatStatsDate(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return '';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(date)}
function showStatsMeta(stats){const achievements=$('.achievements');if(!achievements)return;const updated=formatStatsDate(stats.updatedAt);if(updated){const line=document.createElement('p');line.className='stats-updated';line.textContent=`Live from LeetCode & CodeChef - updated ${updated}`;achievements.after(line)}const leetcodeCard=achievements.querySelectorAll('.stat-card')[1];const breakdown=['easy','medium','hard'].filter(level=>Number(stats.leetcode?.[level])>0);if(leetcodeCard&&breakdown.length){const chips=document.createElement('div');chips.className='stats-breakdown';chips.setAttribute('aria-label','LeetCode difficulty breakdown');breakdown.forEach(level=>{const chip=document.createElement('span');chip.textContent=`${level[0].toUpperCase()+level.slice(1)} ${stats.leetcode[level]}`;chips.append(chip)});leetcodeCard.append(chips)}}
async function loadStats(){try{const response=await fetch(`data/stats.json?t=${Date.now()}`);if(!response.ok)throw new Error('stats unavailable');const stats=await response.json();const leetcode=Number(stats.leetcode?.solved),codechef=Number(stats.codechef?.solved);if(leetcode>0){const counter=$('.achievements .counter[data-target="90"]');if(counter)counter.dataset.target=Math.floor(leetcode)}if(codechef>0){const counter=$('.achievements .counter[data-target="500"]');if(counter)counter.dataset.target=Math.floor(codechef)}showStatsMeta(stats)}catch{ /* file:// and network failures keep the HTML defaults silently */ }}
function initCertificates(){$$('.certificate-link').forEach(button=>button.addEventListener('click',()=>window.open(CERTIFICATE_LINKS[Number(button.dataset.certificate)],'_blank','noopener,noreferrer')))}
function initRocket(){const rocket=$('.rocket-button');if(!rocket)return;rocket.addEventListener('click',()=>{rocket.classList.add('launch');window.scrollTo({top:0,behavior:reducedMotion?'auto':'smooth'});setTimeout(()=>rocket.classList.remove('launch'),1000)})}
function pageHref(){const current=location.pathname.split('/').pop()||'index.html';return pageOrder.includes(current)?current:'index.html'}
function goPage(direction){const index=pageOrder.indexOf(pageHref()),next=pageOrder[(index+direction+pageOrder.length)%pageOrder.length];document.body.classList.add('page-leaving');setTimeout(()=>location.href=next,180)}
function initGestures(){let startX=0,startY=0;addEventListener('touchstart',event=>{startX=event.changedTouches[0].clientX;startY=event.changedTouches[0].clientY},{passive:true});addEventListener('touchend',event=>{const dx=event.changedTouches[0].clientX-startX,dy=event.changedTouches[0].clientY-startY;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.4)goPage(dx<0?1:-1)},{passive:true});addEventListener('keydown',event=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(event.key==='ArrowRight')goPage(1);if(event.key==='ArrowLeft')goPage(-1);if(event.key.toLowerCase()==='t')$('.rocket-button')?.click()})}
function initSmoothAnchors(){if(!location.hash)return;requestAnimationFrame(()=>$(location.hash)?.scrollIntoView({behavior:reducedMotion?'auto':'smooth'}))}
function initCardInteractions(){if(!reducedMotion&&matchMedia('(pointer: fine)').matches){ $$('.glass-card').forEach(card=>{card.addEventListener('pointermove',event=>{const box=card.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;card.style.transform=`perspective(700px) rotateY(${x*3}deg) rotateX(${y*-3}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}$$('.glass-card,.button').forEach(element=>element.addEventListener('click',event=>{if(matchMedia('(pointer: coarse)').matches){const ripple=document.createElement('span'),size=Math.max(element.clientWidth,element.clientHeight),box=element.getBoundingClientRect();ripple.className='ripple';ripple.style.width=ripple.style.height=`${size}px`;ripple.style.left=`${event.clientX-box.left-size/2}px`;ripple.style.top=`${event.clientY-box.top-size/2}px`;element.style.position='relative';element.style.overflow='hidden';element.append(ripple);setTimeout(()=>ripple.remove(),600)}}))}
function initFooterContact(){const footer=$('.site-footer');if(footer&&!footer.querySelector('.footer-contact')){const contact=document.createElement('span');contact.className='footer-contact';contact.innerHTML='<a href="mailto:shreneekdesai@gmail.com" target="_blank" rel="noopener noreferrer">Email</a> · <a href="https://linkedin.com/in/shreneekdesai" target="_blank" rel="noopener noreferrer">LinkedIn</a> · <a href="https://github.com/shreneekdesai" target="_blank" rel="noopener noreferrer">GitHub</a>';footer.insertBefore(contact,footer.lastElementChild)}}
initMenu();initTheme();initReveal();initProgress();initTyping();initCertificates();initRocket();initGestures();initSmoothAnchors();initCardInteractions();initFooterContact();loadStats().finally(initCounters);
